### ISSUE TITLE
Support retrieving directory name of a model

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#40]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/40)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
A model SDF usually contains URI pointing to resources or other models in the form of `model://model_name/path/to/file`

e.g.

~~~
model://beer/meshes/materials/scripts/beer.material
~~~

In ign-fuel, the model names are capitalized, e.g in the case above, `Beer`. So when parsing an SDF file and looking up resources to download from ign-fuelserver, it is not possible to identify the correct model to download unless there is a way to get the model directory path of a model

**Comment by chapulina** [comment]
This issue is no longer 100% valid, because the directory name now matches the model name on Fuel.

For example, this model:

https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Post%20office

Ends up in:

`~/.ignition/fuel/fuel.ignitionrobotics.org/OpenRobotics/models/Post office/`

The remaining issue is, if you download that model and check the SDF, it has the old directory name:

`<uri>model://post_office/meshes/post_office.dae</uri>`

I'd say this is something we should have fixed when we renamed the models and uploaded them to Fuel.

---

To avoid any model name at all, since SDFormat 9, a URI relative to the SDF file should work:sparkle: , for example:

`<uri>meshes/post_office.dae</uri>`

:sparkle: It works for Ignition Gazebo 3+, but not yet for Gazebo 11 (https://github.com/osrf/gazebo/issues/2718).
